// 中文美食数据
export const chineseFoodData = {
  meals: [
    {
      idMeal: "1001",
      strMeal: "宫保鸡丁",
      strMealThumb: "https://images.unsplash.com/photo-1603073113959-a3e4123d7e8c?w=500",
      strCategory: "川菜",
      strArea: "中国",
      strInstructions: "1. 将鸡胸肉切成小块,用料酒、酱油、淀粉腌制15分钟。\n2. 准备花生米、干辣椒、葱姜蒜。\n3. 热锅凉油,炒香花椒和干辣椒。\n4. 加入鸡肉快速翻炒至变色。\n5. 加入葱姜蒜,倒入调好的酱汁(酱油、醋、糖、水淀粉)。\n6. 最后加入花生米翻炒均匀即可出锅。",
      strIngredient1: "鸡胸肉",
      strIngredient2: "花生米",
      strIngredient3: "干辣椒",
      strIngredient4: "花椒",
      strIngredient5: "葱姜蒜",
      strIngredient6: "酱油",
      strIngredient7: "料酒",
      strIngredient8: "白糖",
      strIngredient9: "醋",
      strIngredient10: "淀粉",
      strMeasure1: "300克",
      strMeasure2: "100克",
      strMeasure3: "10个",
      strMeasure4: "1小勺",
      strMeasure5: "适量",
      strMeasure6: "2勺",
      strMeasure7: "1勺",
      strMeasure8: "1勺",
      strMeasure9: "1勺",
      strMeasure10: "1勺",
      strYoutube: ""
    },
    {
      idMeal: "1002",
      strMeal: "麻婆豆腐",
      strMealThumb: "https://images.unsplash.com/photo-1580731872290-93a18e4f5bc2?w=500",
      strCategory: "川菜",
      strArea: "中国",
      strInstructions: "1. 豆腐切小块,焯水备用。\n2. 锅中放油,炒香豆瓣酱。\n3. 加入肉末炒至变色。\n4. 倒入高汤和豆腐,煮3-5分钟。\n5. 加入蒜末、葱花。\n6. 用水淀粉勾芡,撒上花椒粉即可。",
      strIngredient1: "嫩豆腐",
      strIngredient2: "猪肉末",
      strIngredient3: "郫县豆瓣酱",
      strIngredient4: "葱蒜",
      strIngredient5: "花椒粉",
      strIngredient6: "淀粉",
      strIngredient7: "高汤",
      strMeasure1: "400克",
      strMeasure2: "100克",
      strMeasure3: "2勺",
      strMeasure4: "适量",
      strMeasure5: "1勺",
      strMeasure6: "适量",
      strMeasure7: "300ml",
      strYoutube: ""
    },
    {
      idMeal: "1003",
      strMeal: "红烧肉",
      strMealThumb: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
      strCategory: "家常菜",
      strArea: "中国",
      strInstructions: "1. 五花肉切块,焯水去腥。\n2. 锅中放少量油,加冰糖炒糖色。\n3. 加入五花肉翻炒上色。\n4. 加入葱姜、八角、桂皮、香叶。\n5. 倒入料酒和酱油,加水没过肉。\n6. 大火烧开转小火炖1小时,大火收汁即可。",
      strIngredient1: "五花肉",
      strIngredient2: "冰糖",
      strIngredient3: "八角",
      strIngredient4: "桂皮",
      strIngredient5: "香叶",
      strIngredient6: "葱姜",
      strIngredient7: "料酒",
      strIngredient8: "酱油",
      strMeasure1: "500克",
      strMeasure2: "30克",
      strMeasure3: "2个",
      strMeasure4: "1小块",
      strMeasure5: "2片",
      strMeasure6: "适量",
      strMeasure7: "2勺",
      strMeasure8: "3勺",
      strYoutube: ""
    },
    {
      idMeal: "1004",
      strMeal: "糖醋排骨",
      strMealThumb: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=500",
      strCategory: "家常菜",
      strArea: "中国",
      strInstructions: "1. 排骨洗净切块,焯水去血沫。\n2. 锅中放油,煎至两面金黄。\n3. 加入葱姜蒜爆香。\n4. 倒入调好的糖醋汁(醋3勺、糖2勺、酱油1勺、料酒1勺)。\n5. 加水没过排骨,大火烧开转中火焖煮30分钟。\n6. 大火收汁,撒上芝麻即可。",
      strIngredient1: "排骨",
      strIngredient2: "白糖",
      strIngredient3: "陈醋",
      strIngredient4: "酱油",
      strIngredient5: "料酒",
      strIngredient6: "葱姜蒜",
      strIngredient7: "芝麻",
      strMeasure1: "500克",
      strMeasure2: "2勺",
      strMeasure3: "3勺",
      strMeasure4: "1勺",
      strMeasure5: "1勺",
      strMeasure6: "适量",
      strMeasure7: "少许",
      strYoutube: ""
    },
    {
      idMeal: "1005",
      strMeal: "西红柿炒鸡蛋",
      strMealThumb: "https://images.unsplash.com/photo-1607620911907-7b2c72ab0bdf?w=500",
      strCategory: "家常菜",
      strArea: "中国",
      strInstructions: "1. 西红柿切块,鸡蛋打散加少许盐。\n2. 热锅凉油,炒鸡蛋至蓬松盛出。\n3. 锅中再放油,炒西红柿至出汁。\n4. 加入少许糖和盐调味。\n5. 倒入炒好的鸡蛋,翻炒均匀。\n6. 撒上葱花即可出锅。",
      strIngredient1: "西红柿",
      strIngredient2: "鸡蛋",
      strIngredient3: "葱花",
      strIngredient4: "盐",
      strIngredient5: "白糖",
      strMeasure1: "2个",
      strMeasure2: "3个",
      strMeasure3: "适量",
      strMeasure4: "适量",
      strMeasure5: "少许",
      strYoutube: ""
    },
    {
      idMeal: "1006",
      strMeal: "鱼香肉丝",
      strMealThumb: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=500",
      strCategory: "川菜",
      strArea: "中国",
      strInstructions: "1. 猪肉切丝,用料酒、淀粉腌制。\n2. 木耳、胡萝卜、青椒切丝。\n3. 调鱼香汁:酱油、醋、糖、水淀粉、豆瓣酱。\n4. 热锅炒肉丝至变色盛出。\n5. 炒香葱姜蒜,加入配菜翻炒。\n6. 倒入肉丝和鱼香汁,快速翻炒均匀即可。",
      strIngredient1: "猪里脊",
      strIngredient2: "木耳",
      strIngredient3: "胡萝卜",
      strIngredient4: "青椒",
      strIngredient5: "葱姜蒜",
      strIngredient6: "豆瓣酱",
      strIngredient7: "酱油",
      strIngredient8: "醋",
      strIngredient9: "白糖",
      strIngredient10: "淀粉",
      strMeasure1: "200克",
      strMeasure2: "50克",
      strMeasure3: "1根",
      strMeasure4: "1个",
      strMeasure5: "适量",
      strMeasure6: "1勺",
      strMeasure7: "2勺",
      strMeasure8: "2勺",
      strMeasure9: "1勺",
      strMeasure10: "适量",
      strYoutube: ""
    },
    {
      idMeal: "1007",
      strMeal: "水煮鱼",
      strMealThumb: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500",
      strCategory: "川菜",
      strArea: "中国",
      strInstructions: "1. 鱼片加盐、蛋清、淀粉腌制。\n2. 豆芽、生菜焯水铺底。\n3. 锅中炒香豆瓣酱、花椒。\n4. 加高汤煮开,下鱼片煮熟。\n5. 鱼片连汤倒在菜上。\n6. 撒上辣椒面、花椒,浇热油激香即可。",
      strIngredient1: "草鱼",
      strIngredient2: "豆芽",
      strIngredient3: "生菜",
      strIngredient4: "豆瓣酱",
      strIngredient5: "花椒",
      strIngredient6: "干辣椒",
      strIngredient7: "蛋清",
      strIngredient8: "淀粉",
      strMeasure1: "500克",
      strMeasure2: "200克",
      strMeasure3: "150克",
      strMeasure4: "2勺",
      strMeasure5: "1勺",
      strMeasure6: "适量",
      strMeasure7: "1个",
      strMeasure8: "适量",
      strYoutube: ""
    },
    {
      idMeal: "1008",
      strMeal: "酸菜鱼",
      strMealThumb: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500",
      strCategory: "川菜",
      strArea: "中国",
      strInstructions: "1. 草鱼片成片,加盐、料酒、蛋清腌制。\n2. 酸菜切丝,挤干水分。\n3. 锅中炒香酸菜、姜蒜。\n4. 加高汤煮开,调味。\n5. 下鱼片煮至变色。\n6. 撒上葱花、香菜即可。",
      strIngredient1: "草鱼",
      strIngredient2: "酸菜",
      strIngredient3: "姜蒜",
      strIngredient4: "泡椒",
      strIngredient5: "高汤",
      strIngredient6: "香菜",
      strIngredient7: "葱花",
      strMeasure1: "500克",
      strMeasure2: "200克",
      strMeasure3: "适量",
      strMeasure4: "适量",
      strMeasure5: "800ml",
      strMeasure6: "适量",
      strMeasure7: "适量",
      strYoutube: ""
    },
    {
      idMeal: "1009",
      strMeal: "回锅肉",
      strMealThumb: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500",
      strCategory: "川菜",
      strArea: "中国",
      strInstructions: "1. 五花肉煮至八成熟,切薄片。\n2. 青蒜、青红椒切段。\n3. 锅中少油,煸炒五花肉至出油卷边。\n4. 加豆瓣酱、豆豉炒香。\n5. 加青蒜、青红椒快速翻炒。\n6. 加少许糖提鲜即可出锅。",
      strIngredient1: "五花肉",
      strIngredient2: "青蒜",
      strIngredient3: "青红椒",
      strIngredient4: "豆瓣酱",
      strIngredient5: "豆豉",
      strIngredient6: "白糖",
      strMeasure1: "300克",
      strMeasure2: "100克",
      strMeasure3: "2个",
      strMeasure4: "1勺",
      strMeasure5: "少许",
      strMeasure6: "少许",
      strYoutube: ""
    },
    {
      idMeal: "1010",
      strMeal: "小笼包",
      strMealThumb: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500",
      strCategory: "点心",
      strArea: "中国",
      strInstructions: "1. 面粉加水和成面团,醒30分钟。\n2. 猪肉馅加葱姜、酱油、盐、糖调味。\n3. 加入肉皮冻拌匀。\n4. 面团擀成薄皮,包入馅料。\n5. 蒸笼铺湿笼布,摆入包子。\n6. 大火蒸8-10分钟即可。",
      strIngredient1: "面粉",
      strIngredient2: "猪肉馅",
      strIngredient3: "肉皮冻",
      strIngredient4: "葱姜",
      strIngredient5: "酱油",
      strIngredient6: "盐",
      strIngredient7: "白糖",
      strMeasure1: "500克",
      strMeasure2: "300克",
      strMeasure3: "100克",
      strMeasure4: "适量",
      strMeasure5: "2勺",
      strMeasure6: "适量",
      strMeasure7: "少许",
      strYoutube: ""
    },
    {
      idMeal: "1011",
      strMeal: "蛋炒饭",
      strMealThumb: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
      strCategory: "主食",
      strArea: "中国",
      strInstructions: "1. 隔夜米饭打散。\n2. 鸡蛋打散,加少许盐。\n3. 热锅炒鸡蛋至半熟盛出。\n4. 锅中放油,炒米饭至粒粒分明。\n5. 加入鸡蛋、葱花、盐翻炒。\n6. 加少许酱油调色即可。",
      strIngredient1: "米饭",
      strIngredient2: "鸡蛋",
      strIngredient3: "葱花",
      strIngredient4: "酱油",
      strIngredient5: "盐",
      strMeasure1: "300克",
      strMeasure2: "2个",
      strMeasure3: "适量",
      strMeasure4: "1勺",
      strMeasure5: "适量",
      strYoutube: ""
    },
    {
      idMeal: "1012",
      strMeal: "担担面",
      strMealThumb: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500",
      strCategory: "面食",
      strArea: "中国",
      strInstructions: "1. 碎米芽菜、肉末炒香。\n2. 碗中放芝麻酱、酱油、醋、辣椒油、花椒粉。\n3. 煮面,捞出放入调好的碗中。\n4. 浇上炒好的肉末。\n5. 撒上葱花、花生碎。\n6. 拌匀即可食用。",
      strIngredient1: "面条",
      strIngredient2: "猪肉末",
      strIngredient3: "芽菜",
      strIngredient4: "芝麻酱",
      strIngredient5: "辣椒油",
      strIngredient6: "花椒粉",
      strIngredient7: "葱花",
      strIngredient8: "花生碎",
      strMeasure1: "200克",
      strMeasure2: "100克",
      strMeasure3: "50克",
      strMeasure4: "2勺",
      strMeasure5: "适量",
      strMeasure6: "适量",
      strMeasure7: "适量",
      strMeasure8: "适量",
      strYoutube: ""
    }
  ]
};
